* Savokos
- Syntakse -- funkcija siejanti aktyvius symbolius ir parsinimo metodus
- Parsinimo metodas -- algoritmas surenkantis visa LaTeX skripto reiskini, kuris
  parsinimo metu isskiriamas is bendro konteksto.
- Reiskinys -- LaTeX skripto objektas turintis vidine struktura.
  Reiskiniu tipai:
  * Paprastos strukturos reiskiniai -- reiskiniai neturintys sudetingos ar
    strukturos ir savo atskiros syntakses (inline komentarai, inline_verbatimai, tekstas)
  * Gilios strukturos reiskiniai -- reiskiniai galintys tureti savo atskira syntakse,
    ju struktura gali sudaryti kiti paprastos arba gilios strukturos reiskiniai.
    Taip pat turintys skirtukus, skriptiniame faile isskiriancius juos is isorinio 
    reiskinio
* Parsinimo procesas
** Parsinimo sirdis
   Funkcijai =parse=  perduodamas algoritmas tikrinantis ar symbolis i kuri ziurima nera
   uzdarancio esama reiskini skirtuko pradzia.
   Skirtukai:
   - aktyvus symboliai ($...$, {...})
   - aktyviu symboliu kombinacijos ($$...$$)
   - TeX'ines komandos:
     + griesti switch'ai (\iffalse...\fi, \[ ... \], \( ... \))
     + enviromentai (\begin{aplinka}...\end{aplinka})
       
   Funkcija parse, savo veikimo metu su savimi nesasi:
   - parsinamo reiskinio syntakse.
     tabular tipo objekte & -> kolonos skirtukas
     tekstiniame objekte $ -> matematinio reiksinio pradzia
     matematiniame reiskinyje $ -> matematinio reiskinio pabaiga
     verbatiminiame reiskinyje % -> symbolis
     tekstiniame reikinyje % -> komentaro pradzia 
     index argumente % -> dar kita reiksme ir t.t.
   - nuoroda i parsinama eilute
   - parsinimo objekta priklausanti esamam reiskiniui ir kuriama parsinimo metu.
     Objektu pavyzdziai:
     + inline matematika =...$ a + b $...=
     + apskliaustas reiskinys =...{ tekstas }...=
       -- gali buti komandos argumentas, arba siaip apskliaustas
       reiskinys
     + 
   - uzdarymo ieskanti algoritma

*** Algoritmas 
    1) Tikrinama ar esamas reiskinys neuzdaromas, jei taip:
       - grazinamas pilnas reiskinys (a) =objekto pavidalu= (reiskinys) su suparsintu turiniu 
	 ir sio (b) =objekto skriptines reprezentacijos ilgis=, 
	 (c) =objekta uzdarancio reiskinio ilgis=
       jei ne:
       - kreipiamasi i funkcija =do_the_right_thing= perduodant esama =syntakse=, 
	 =nuoroda i esama objekta=,  =nuoroda i tiriama symboli=.
    2) =do_the_right_thing= funkcijos pagrindines uzduotys:
       - atpazinti ar symbolis i kuri ziurima yra aktyvus ar ne
       - jei esamas symbolis neaktyvus tai surinkti visa nuosekliai einancia neaktyviu
	 symboliu seka ir grazinti paprastos strukturos objekta, su priskirtu tipu 
	 -- sakykim =tekstas=
       - jei symbolis aktyvus, tai kreiptis i esamoje syntakseje aprasyta algoritma surenkati
	 LaTeX skripto dali sudarancia tam tikra reiskini
    3) =Iskviestas metodas= surenka atitinkama reiskini ir grazina ji objekto pavidalu, bei sio
       objekto ilgi.
    4) =do_the_right_thing= grazina =parse= procesui =ilgi surinkto objekto=,
       kad nusokti i koordinate uz surinkto objekto ir prideda
       surinkta vidini objekta prie =parse= kuriamo objekto.

